; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:nucleo_l476rg]
platform = ststm32@19.4.0
board = nucleo_l476rg
framework = arduino
build_type = debug
build_flags = 
	-Wall       ; affichage de tous les Warnings
    -Wextra     ; recherches avancée des Warnings
    -O0         ; niveau d'optimisation minimal pour faciliter le suivi du fil d'exécution en debug
	-ggdb3      ; génération d'informations de débogage de niveau 3 pour gdb
	-g          ; génération d'informations de débogage dans l'exécutable
	-Wl,--no-warn-rwx-segments  ; désactivation warning du linkeur 
	-Wno-deprecated  ; pas d'avertissements pour l'utilisation de fonctions dépréciées

monitor_speed = 115200
monitor_echo = yes

debug_tool = stlink

debug_init_break = tbreak main				; pause imposée sur l'entrée de la fonction principale

debug_extra_cmds = 							; commandes GDB
    set *(uint32_t*)0xE000EDFC = 0x01000000	; activation DWT 
    set *(uint32_t*)0xE0001000 = 1			; activation CYCCNT (compteur de cycles CPU (cycles processeur))
	undisplay								; supprime tous les affichages
	display *(uint32_t*)0xE0001004			; ajoute l'affichage du compteur CPU
											;
											; Commandes possibles dans l'onglet "DEBUG CONSOLE"
											; taper la commande 
											; 		set *(uint32_t*)0xE0001004 = 0
											; pour remettre à zéro le compteur de cycles CPU
											;
											; taper la commande
											;		print *(uint32_t*)0xE0001004
											; pour forcer l'affichage du compteur de cycles CPU
monitor_filters = 
	direct
	time
	log2file


;upload_protocol = mbed ; chargement par bootloader pour récupérer d'un crash des lignes SWDIO/SWCLK